# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/find_friend
    username: root
    password: "011026"
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
