spring:
  profiles:
    active: dev
  application:
    name: find-friend-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/find_friend?serverTimezone=Asia/Shanghai
    username: root
    password: "011026"
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    port: 6379
    host: localhost
    database: 1
server:
  port: 2318
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
